# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a48ab5b0-f73c-4895-9474-f1cfb2b6ef40";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a48ab5b0-f73c-4895-9474-f1cfb2b6ef40".device = "/dev/disk/by-uuid/a48ab5b0-f73c-4895-9474-f1cfb2b6ef40";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F306-BAFB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
